[package]
name = "nixhub"
version = "0.1.0"
authors = ["Amit Aryeh Levy <amit@amitlevy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {"version"= "*", features=["yaml"]}
reqwest = "*"
tokio = {"version"= "0.2", features=["macros", "signal"]}
hyper = "*"
